package lexicalAnalyzer;

public enum TokenType {

    // Keywords
    KEYWORD_CLASS,
    KEYWORD_EXTENDS, 
    KEYWORD_IS,
    KEYWORD_END,
    KEYWORD_VAR,
    KEYWORD_IF,
    KEYWORD_THEN,
    KEYWORD_ELSE,
    KEYWORD_WHILE,
    KEYWORD_LOOP,
    KEYWORD_RETURN,
    KEYWORD_METHOD,
    KEYWORD_THIS,
    KEYWORD_INTEGER,
    KEYWORD_REAL,
    KEYWORD_STRING,
    KEYWORD_BOOLEAN,
    KEYWORD_TRUE,
    KEYWORD_FALSE,
    KEYWORD_ARRAY,
    KEYWORD_LIST,
    KEYWORD_NULL,

    // Punctuation
    PUNCTUATION_SPACE,
    PUNCTUATION_LINE_BREAK,
    PUNCTUATION_TABULATION,
    PUNCTUATION_DOUBLE_QUOTE,
    PUNCTUATION_SEMICOLON,
    PUNCTUATION_COMMA,
    PUNCTUATION_EQUAL,
    PUNCTUATION_LEFT_PARENTHESIS, // (
    PUNCTUATION_RIGHT_PARENTHESIS, // )
    PUNCTUATION_LEFT_BRACKET, // [
    PUNCTUATION_RIGHT_BRACKET, // ]
    PUNCTUATION_DOT,
    PUNCTUATION_SEMICOLON_EQUAL,

    // Literals
    LITERAL_INTEGER,
    LITERAL_REAL,
    LITERAL_STRING,

    // Identifiers
    IDENTIFIER,

    // Special tokens
    EOF, // End of file
    ERROR // Error token (e.g., unrecognized character)
}
